### ISSUE TITLE
Model optimization

### ISSUE THREAD

**Issue by margaretmz** [margaretmz/segmentation-style-transfer#1]

**Comment by sayakpaul** [comment]
The style transfer TF Lite models are optimized already (they have int8 quantized versions). [This tutorial](https://www.tensorflow.org/lite/models/style_transfer/overview) actually uses them. 

The segmentation models are yet to be optimized. They haven't been because of the unavailability of the quantized kernels that are required for int8 quantization as far as I know. But I will keep trying. 

@margaretmz update: I just tried to quantize the models with int8 quantization with a representation dataset, the resultant TF Lite model's size is actually bigger than the one quantized with dynamic range quantization.

**Comment by sayakpaul** [comment]
Float16 and Int8 models have been generated. The conversion notebook can be found [here](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/DeepLabV3/DeepLab_TFLite_COCO.ipynb). The models can be found [here](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/tag/v0.3.0).

**Comment by sayakpaul** [comment]
The optimized models were just added to TensorFlow Hub. They are accessible from the links below:
- https://tfhub.dev/s?q=deeplabv3-mobilenetv2_dm05
- https://tfhub.dev/s?dataset=pascal-voc-2012&q=deeplabv3-mobilenetv2 (PASCAL VOC 2012 only)
